# Use postgres/example user/password credentials
version: "3.9"

services:
  redis:
    image: redis
    container_name: redis_service
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: always

  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD_FILE=${POSTGRES_PASSWORD_FILE}
    volumes:
      - pgdata:/var/lib/postgresql/data
    secrets:
      - db_password

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  rabbitmq:
    restart: always
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      


volumes:
  pgdata:
  redis_data:

secrets:
  db_password:
    file: postgres_password.txt